jms_serializer:
    metadata:
        directories:
            LhgTracker:
                namespace_prefix: "KimaiPlugin\\LhgTrackerBundle"
                path: "@LhgTrackerBundle/Resources/config/serializer"
        # warmup:
        #     paths:
        #         included:
        #             - "%kernel.root_dir%/../var/plugins/LhgTrackerBundle/Entity/"
